services:
  kestra:
    image: kestra/kestra:latest
    pull_policy: always
    command: server local
    user: root
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - C:/Temp:/tmp